# Generated by Django 5.1.3 on 2024-11-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("primary_worker", "Primary Worker"),
                    ("manager", "Manager"),
                    ("vet", "Vet"),
                    ("auditor", "Auditor"),
                    ("guest", "guest"),
                ],
                max_length=50,
            ),
        ),
    ]
