# Generated by Django 5.1.3 on 2024-11-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_no", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("health_status", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=20,
                    ),
                ),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dam_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dam_offspring",
                        to="goats.goat",
                    ),
                ),
                (
                    "sire_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sire_offspring",
                        to="goats.goat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalGoat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_no", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("health_status", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("update_date", models.DateTimeField()),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                (
                    "goat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="goats.goat",
                    ),
                ),
            ],
        ),
    ]
