# Generated by Django 5.1.3 on 2024-11-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goat",
            old_name="dam_id",
            new_name="dam",
        ),
        migrations.RenameField(
            model_name="goat",
            old_name="sire_id",
            new_name="sire",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="deleted_date",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="update_date",
        ),
        migrations.AlterField(
            model_name="goat",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="goat",
            name="status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="goat",
            name="tag_no",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="goat",
            name="weight",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="GoatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_no", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.FloatField()),
                ("health_status", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("update_date", models.DateTimeField(auto_now_add=True)),
                (
                    "dam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_dam",
                        to="goats.goat",
                    ),
                ),
                (
                    "goat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="goats.goat",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_sire",
                        to="goats.goat",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HistoricalGoat",
        ),
    ]
