# Generated by Django 5.1.3 on 2024-11-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0002_rename_dam_id_goat_dam_rename_sire_id_goat_sire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goat",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
