# Generated by Django 5.1.3 on 2024-11-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0004_goat_deleted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="goathistory",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
