# Generated by Django 5.1.3 on 2024-11-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0005_goathistory_deleted_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goat",
            old_name="dam",
            new_name="dam_id",
        ),
        migrations.RenameField(
            model_name="goat",
            old_name="sire",
            new_name="sire_id",
        ),
        migrations.AlterField(
            model_name="goat",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="goat",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="goat",
            name="tag_no",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="goat",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name="HistoricalGoat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_no", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("health_status", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("update_date", models.DateTimeField()),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                ("change_date", models.DateTimeField(auto_now_add=True)),
                (
                    "goat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="goats.goat",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GoatHistory",
        ),
    ]
