# Generated by Django 5.1.3 on 2024-11-08 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goats", "0006_rename_dam_goat_dam_id_rename_sire_goat_sire_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgoat",
            name="change_date",
        ),
        migrations.RemoveField(
            model_name="historicalgoat",
            name="deleted_date",
        ),
    ]
